; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.13 on Sun Oct 16 2022 20:05:35 GMT-1000 (Hawaii-Aleutian Standard Time)
; Wait for set temperatures to be reached
M116 P0

